### ISSUE TITLE
Exception is raised on Windows during compile phase

### ISSUE THREAD

**Issue by veetow** [sous-chefs/cron#112]
### Cookbook version
latest

### Chef-client version
12.16.42

### Platform Details
Windows any

### Scenario:
We have a recipe which supports both Linux and Windows.  That recipe uses the `cron_d` resource, but has a guard clause to ensure it converges only on Linux.  This exception is raised in the compile phase on our Windows nodes:

https://github.com/chef-cookbooks/cron/blob/master/resources/d.rb#L53-L55

### Steps to Reproduce:
```ruby

# This raises the exception
cron_d scheduled_job_name do
  user    'root'
  minute  '*'
  hour    '*'
  command 'echo hello github'

  not_if { node['platform_family'] == 'windows' }
end

# This does not
unless node['platform_family'] == 'windows'
  cron_d scheduled_job_name do
    user    'root'
    minute  '*'
    hour    '*'
    command 'echo hello github'
  end
end
```

### Expected Result:
A guard clause should not cause the exception to be raised.

### Actual Result:
The exception is raised.

**Comment by tas50** [comment]
Hmm that's certainly not the intended behavior. I'll have a look post ChefConf
