### ISSUE TITLE
cron.deny template rendering fails

### ISSUE THREAD

**Issue by sspans** [sous-chefs/cron#113]
### Cookbook version
6.1.1

### Chef-client version
12.22.3

### Platform Details
CentOS 7

### Scenario:
cron_manage deny fails because the first username is passed as nil.

### Steps to Reproduce:
Use mulitple cron_manage statements

### Expected Result:
A working chef run with a cron.deny file

### Actual Result:
         
           ================================================================================
           Error executing action `create` on resource 'template[/etc/cron.deny]'
           ================================================================================
           
           Chef::Mixin::Template::TemplateError
           ------------------------------------
           comparison of NilClass with String failed
           
           Resource Declaration:
           ---------------------
           # In /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.22.3/lib/chef/dsl/declare_resource.rb
           
           158:         declare_resource(type, name, created_at, run_context: run_context, &resource_attrs_block)
           159:       end
           
           Compiled Resource:
           ------------------
           # Declared in /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.22.3/lib/chef/dsl/declare_resource.rb:158:in `rescue in edit_resource'
           
           template("/etc/cron.deny") do
             action [:nothing]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             source "cron_manage.erb"
             cookbook "cron"
             variables {"users"=>[nil, "pdezoete", "rhuyerma"]}
             declared_type :template
             cookbook_name "matrixreloaded"
             owner nil
             group nil
             mode "0600"
             path "/etc/cron.deny"
             verifications []
           end
           
           Template Context:
           -----------------
           on line #2
             1: # Generated by Chef. Changes will be overwritten.
             2: <% @users.sort.uniq.each do |user| -%>
             3: <%= user %>
             4: <% end -%>
           
           System Info:
           ------------
           chef_version=12.22.3
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
           program_name=chef-client worker: ppid=1401;start=09:39:23;
           executable=/opt/chef/bin/chef-client

**Comment by skadz** [comment]
Seeing the same issue on cron.allow.  If you look closely, you see the first user is nil, even though (at least in my case), I am just passing a string of one user.

**Comment by skadz** [comment]
I'm now assuming this is a Chef 12 issue and it will go away when I (we) update.  Pushed down to 5.0.1 and it works great (the last one that has Chef 12 tests)
