### ISSUE TITLE
Permissions on cron.allow and cron.deny prohibit /usr/bin/crontab from reading when the binary is setgid rather than setuid

### ISSUE THREAD

**Issue by Entreiu** [sous-chefs/cron#120]
### Cookbook version
6.3.0

### Chef-client version
15.8.23

### Platform Details
Ubuntu 18.04

### Scenario:
The mode on /usr/bin/crontab is this:
```
vagrant@default-ubuntu-1804:~$ stat -c '%U:%G %A' /usr/bin/crontab
root:crontab -rwxr-sr-x
```

The cron.allow and cron.deny files are set with mode 0600, prohibiting group members from reading them. Since Ubuntu installs the crontab binary with setgid rather than setuid, the files are unreadable. When the crontab binary cannot read the files, they are ignored. This permits all users to have a crontab even if prohibited by these files.

### Steps to Reproduce:
Use this cookbook on an Ubuntu 18.04 host
Deny all non-root users by using:
```
cron_manage 'root' do
  action :allow
end
cron_manage 'ALL' do
  action :deny
end
```
### Expected Result:
The user should be denied the ability to install a crontab

### Actual Result:
non-root users are permitted to install a crontab

**Comment by samolives** [comment]
print("cribbage")
