### ISSUE TITLE
Seeing issue with the deployment on chef 12.22.1 after recent update to this cookbook

### ISSUE THREAD

**Issue by vpilania** [sous-chefs/cron#134]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Getting NoMethod Error  -----> unified_mode true

## :pancakes: Cookbook version

Version of the cookbook where you are encountering the issue. 7.0.0

## :woman_cook:  Chef-Infra Version

Version of chef-client in your environment. - 12.22.1

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.

chef_version=12.22.1
platform=amazon
platform_version=2018.03

## :heavy_plus_sign: Additional context

Getting this error from this morning 

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/cron/resources/access.rb
================================================================================
NoMethodError
-------------
undefined method `unified_mode' for #<Class:0x0000000004d93790>
Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/cron/resources/access.rb:24:in `class_from_file'
Relevant File Content:
----------------------
/var/chef/cache/cookbooks/cron/resources/access.rb:
 17:  # Unless required by applicable law or agreed to in writing, software
 18:  # distributed under the License is distributed on an "AS IS" BASIS,
 19:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 20:  # See the License for the specific language governing permissions and
 21:  # limitations under the License.
 22:  #
 23:
 24>> unified_mode true
 25:
 26:  property :user, String,
 27:            name_property: true
 28:
 29:  action :allow do
 30:    with_run_context :root do
 31:      edit_resource(:template, '/etc/cron.allow') do |new_resource|
 32:        source 'cron_manage.erb'
 33:        cookbook 'cron'

**Comment by ramereth** [comment]
Resolved in #135
